# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '19.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm build
    npm run test
  displayName: 'build and test'
  env:
    NPM_TOKEN: $(SecretNpmToken)