# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- feature/*

pr:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0

- task: NodeTool@0
  inputs:
    versionSpec: '19.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm build
    npm run test
  displayName: 'build and test'
  condition: succeeded()
  env:
    NPM_TOKEN: $(SecretNpmToken)

- script: |
    npm run storybook:build
    npm run vrt:snapshot
    npm run vrt:run
  displayName: 'visual regression test'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  env:
    REG_NOTIFY_CLIENT_ID: $(RegNotifyClientId)
    REG_STORAGE_ACCOUNT_KEY: $(RegStorageAccountKey)