version: '3'
services:
  front:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - 3000 
    volumes:
      - .:/workspace
      - /workspace/node_modules
    command: /bin/sh -c "npm run build;while sleep 1000; do :; done" 
    container_name: visualize_effort_frontend_server
    environment:
      GOOGLE_CLIENT_ID: 1038036987590-67hu5cedcmtqmuc77s9kvc2dhthl1gv4.apps.googleusercontent.com
      BASE_BACKEND_PATH: /api
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - backend
      - front
  backend:
    image: harunari/effort_visualizer:stable-550
    expose:
      - 8080
    container_name: effort_visualizer_backend
    environment: 
      DB_SERVERNAME: effort_visualizer_rdb
      DB_USERID: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: mysecretpassword
      GOOGLE_CLIENT_ID: 1038036987590-67hu5cedcmtqmuc77s9kvc2dhthl1gv4.apps.googleusercontent.com
      RUST_LOG: debug
    depends_on:
      - rdb
  rdb:
    image: harunari/effort_visualizer_database:stable
    container_name: effort_visualizer_rdb
    volumes:
      - databsae_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword
    expose:
      - 5432
volumes:
  databsae_volume:
    driver: local