version: '3'
services:
  front:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
     - "3000"  
    volumes:
      - .:/workspace
      - /workspace/node_modules
    command: /bin/sh -c "npm run build;while sleep 1000; do :; done" 
    container_name: visualize_effort_frontend_server
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - front
